### ISSUE TITLE
getting unknown fragment lint error

### ISSUE THREAD

**Issue by waynezhang1995** [graphql/graphiql#2071]
## Actual Behavior
we are using Relay and after the recent updates(starting from version 0.3.23), all the fragments are getting flagged as `unknown fragment`.

## Specifications

  - GraphQL for VSCode Extension Version: > 0.3.23
  - VSCode Version: Version: 1.61.0 (Universal)
  - OS Name: Mac OS
  - OS Version: Big sur 11.6.1
  - graphql config filename and format example:

**Comment by acao** [comment]
I think I have a fix, I will need to do more extensive testing, but #2072 I think will address this and many things.

**Comment by acao** [comment]
Nope. No luck on this one tonight. I have some leads though. Needs way more unit tests

**Comment by esquevin** [comment]
Thank for your efforts anyway =)
Meanwhile I've configured `documents` and don't have issues anymore

**Comment by acao** [comment]
@esquevin exciting to hear!

I think I might just document this as a breaking change then. I think this will be the more `graphql-config` way to do this, and help us reduce unnecessary resource churn by parsing catch-all blobs of files.

**Comment by ernieturner** [comment]
@esquevin Do you have an example of what you set your `documents` value to in your config? I'm trying to get this to work via that method but I'm still having troubles. All of the fragments I use are in `*.graphql.ts` files but setting the config to `documents: ["**/*.graphql.ts"]` doesn't seem to work for me. Curious if I'm doing something wrong here.

**Comment by esquevin** [comment]
I'm using this

```
{ 
  "schema": "./graphql-schema.json",
  "documents": "src/**/*.{graphql,js,ts,jsx,tsx}"
 }
```

**Comment by eMerzh** [comment]
go the same issue here... 

if i define no dcoument , the output of the  graphql-language-service-usage-logs is 👌  but then i get a lot of unknown fragment
if i define for example documents: './src/**/*.jsx' (where my graphq`` tags are .... ) then i got :
>Unable to find any GraphQL type definitions for the following pointers:
> - ./src/**/*.jsx

but my editor does not show any error (while showing doc, ... as it should)

**Comment by eMerzh** [comment]
sorry for double notif, 
but i also just encounter also a project where fragments are kinda managed outside of regular lib... 
i know this is probably not supported but evertything else works (complete, warning, doc, ...)but i have the lint yelling at me for the fragments.

If i could silence them maybe it can "solve" both problems

**Comment by xorander00** [comment]
I'm running into this issue myself right now. Figured I'd throw in my $0.02.  
  
When I first open a document (e.g. simple query with fragment spread field selection), it shows the ol' "Unknown fragment ..." error. Then I found that if I open the file where I have my fragments defined and immediately save it, then go back go the query document and save that one, it seems to pick up the fragment definitions and the errors disappear.  Just to check I tried auto-completions/suggestions and it worked fine and showed fragments in the list.
  
I'm on FreeBSD 13.0/amd64 and NeoVim 0.6.0 with the latest graphql-lsp. My graphql config is as follows...
  
```json
{
  "schema": "./src/graphql/generated/schema.json",
  "documents": [
    "./src/graphql/documents/*.graphql",
    "./src/graphql/documents/**/*.graphql"
  ]
}
```

**Comment by xorander00** [comment]
Just tested it out again a few more times since I wasn't 100% sure it wasn't some weird anomaly. I can confirm that the following happens (in my case at least):  
  
1. Open query document for editing (myQuery.graphql), see LSP report unknown fragment errors.
2. Open document that defines fragments (myFragments.graphql) in same instance of editor+lsp.
3. Insert newline, delete newline, and then save myFragments.graphql.
4. Switch back to myQuery.graphql, insert newline, delete newline, and then save myQuery.graphql.
5. Watch errors instantly disappear and completions are now available for fragment types.

**Comment by eMerzh** [comment]
just wondering if it was related to relay (i use relay) and if it requires some special config in the graphql-config file

**Comment by hiro1107** [comment]
I got this error just because of some VS code plugin. Possibly you can try removing unofficial GraphQL plugins and check if you still see errors or not.

**Comment by acao** [comment]
we fixed the issue with loading from `documents`, there had been a breaking change in `graphql-config` we overlooked, we now support loading the code files properly

**Comment by lewebsimple** [comment]
For anyone stumbling on this issue, removing `ignoreNoDocuments: true` from the graphql.config.js / codegen.ts file solved the issue for me.

**Comment by acao** [comment]
thanks @lewebsimple , we may be able to set this on `loadDocuments()` or set some defaults if this config isn't provided

**Comment by lewebsimple** [comment]
Hmmm … turns out the problem came back after a little while so it’s probably something else. Sorry about the confusion…

**Comment by stephenjason89** [comment]
Hello @acao  I'm having the same issue as well. I only have the graphql schema on my graphql config. If i point the documents to my fragment.ts file then it breaks the auto completion and references.

**Comment by jimisaacs** [comment]
Was getting the same error, found out it's because the extension can't handle loading fragments at symlinks.

Example graphql.config.yml:
```yml
# $schema: https://raw.githubusercontent.com/kamilkisiela/graphql-config/master/config-schema.json
projects:
  myproject:
    schema: ./projects/myproject/schema.graphqls
    documents:
      # This directory contains symlinks to all the graphql files for myproject
      - ./projects/myproject/**/*.graphql
      # The VSCode extension doesn't follow symlinks for fragment inclusion, so need to explicitly include them
      - ../some/other/explicit/location/of/my-project-fragments.graphql
```

**Comment by jimisaacs** [comment]
Maybe it's not the VSCode extension, but the language server 🤷

**Comment by sorenhoyer** [comment]
> ignoreNoDocuments: true

Removing it seems to have worked for me. But what are the implications of not having it set? :-)
